"""empty message

Revision ID: d2e7013572f8
Revises: 8c42b0e5855b
Create Date: 2020-02-12 19:48:38.043298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e7013572f8'
down_revision = '8c42b0e5855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('population', sa.String(length=120), nullable=True),
    sa.Column('longitude', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.String(length=120), nullable=True),
    sa.Column('zipcode', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=120), nullable=True),
    sa.Column('job_place', sa.String(length=120), nullable=True),
    sa.Column('job_pay', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('area_info')
    # ### end Alembic commands ###
